################################################################################
# Main config
################################################################################
baseURL = 'https://www.shrikebyte.com/'
languageCode = 'en-us'
title = 'shrikebyte'
copyright = '© Shrikebyte, LLC'
theme = 'PaperMod'


################################################################################
# Pages
################################################################################

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 10

[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  url = 'posts/'
  weight = 20

[[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = 'contact/'
  weight = 30

[[menu.main]]
  identifier = 'search'
  name = 'Search'
  url = 'search/'
  weight = 40


################################################################################
# PaperMod customizations
################################################################################
[params]

  ShowReadingTime = true
  #ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  env = 'production'
  ShowToc = true
  label.icon = 'logo.png'

  # Disable the automatic post listing from the homepage
  mainSections = []

  [params.assets]
    favicon = "/favicon/favicon.ico"
    favicon16x16 = "/favicon/favicon-16x16.png"
    favicon32x32 = "/favicon/favicon-32x32.png"
    apple_touch_icon = "/favicon/apple-touch-icon.png"


  # Search-related options
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    # limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys = ["title", "permalink", "summary", "content"]


# Need to add this section for search to work
[outputs]
  home = [ 'HTML', 'RSS', 'JSON' ]


# Needed for Github pages
[caches]
  [caches.images]
    dir = ':cacheDir/images'